@extends('frontend.layouts.master')

@section('content')
<div class="container">
<br>
<h3> Tevini  LTD Terms and Conditions </h3>
<p>1. <span class="fw-bold">	OWNERSHIP OF FUNDS TEVINI </span>is a registered charity (charity number 1117850). References in these Terms and Conditions to TEVINI shall be deemed, where the context requires, to refer also to the directors, trustees, consultants to and employees of TEVINI. A donation of funds to TEVINI, which is made by you (whether in cash, by cheque, electronically or by any other means) is an irrevocable charitable donation to TEVINI and such funds immediately become the property of TEVINI. TEVINI will maintain a notional account in your name to identify any donations made by you (“Notional Account”).</p>

    <p>2.	 [TEVINI is under no duty of care to you to maintain funds which have been credited to a Notional Account. In the event that such funds are lost, for example, as a result of the insolvency of a bank with which TEVINI has made deposits, you will have no recourse to TEVINI in respect of such loss.] Interest which is earned on funds donated to TEVINI shall be the property of TEVINI and will not be credited to your Notional Account.</p>

    <p>3.	<span class="fw-bold">TAX REBATES </span> the extent that you have declared that your donations are eligible donations under the HM Revenue & Customs (“HMRC”) Gift Aid scheme, TEVINI will make a claim for basic rate tax from HMRC as permitted by law, and will apply the amount received from HMRC to your Notional Account as if it were a donation of funds to TEVINI. You are responsible for verifying whether or not and the extent to which your donations are eligible under the HMRC Gift Aid Scheme. To the extent that TEVINI apply for and/or receive an amount from HMRC in respect of your donations and such amount is found to have been received in error, TEVINI will be entitled to deduct any such sums from your Notional Account or to require you to make such payment to your Notional Account as may be required to rectify such error. Claims for tax rebates to HMRC are usually submitted monthly and tax credits are shown on statements once the funds have been received by TEVINI. This normally takes one week from the time the claim is submitted but can take longer.</p> 

    <p>4.	<span class="fw-bold">REQUEST FOR PAYMENTS TO CHARITY</span> You may request funds to be paid by TEVINI to a charitable organisation of your selection by means of completion of a voucher provided to you by TEVINI which you may give to a charity or by any electronic means as may be approved from time to time by TEVINI, any such payment will reduce the balance of your Notional Account.</p>

    <p>5.<span class="fw-bold"> DONATIONS TO CHARITY TEVINI </span> may only allocate funds to bona fide charities. This includes the allocation of funds to charities which are registered in the UK with the Charities Commission. TEVINI will have absolute discretion in determining the eligibility of the proposed charity and whether to or when to distribute to the proposed charity. You are responsible for ascertaining whether or not a charity to which you may request an allocation be made, in the form of issuing a voucher or otherwise, is a charity which is eligible to receive funds from TEVINI. Once funds have been transferred to TEVINI, they cannot be returned to you under any circumstances. At no time may you, or any person connected to you, for example, your spouse or close relative, be permitted to derive a benefit from the funds which you donate to TEVINI. No allocation may be made by TEVINI at your request to discharge or satisfy a legally enforceable obligation to which you are party. TEVINI is not and will not be responsible for verifying the charitable status of any charity to which payments are made from your Notional Account or for ascertaining whether or not you or any persons connected to you benefit from such payment.</p> 

    <p>6.	<span class="fw-bold"> SCHOOL FEES </span> Without prejudice to the general statement set out in paragraphs 3 and 4 above, the following shall also apply in relation to school and education related fees. If you are in any doubt of the eligibility of the proposed recipient of an allocation by TEVINI, you should confirm such eligibility prior to transferring funds to TEVINI. a) PRIVATE SCHOOL/COLLEGE FEES TEVINI cannot use funds to pay any private school or college fees whether such fees relate to secular or Hebrew tuition. This also applies to Boarding Schools, Yeshivas and Seminaries and other colleges of higher education, whether in the UK and abroad. b) STATE AIDED SCHOOLS In accordance with current HMRC practice, voluntary contributions requested by State Aided schools in relation to the provision of Kodesh tuition may be paid by donations from TEVINI. c) DONATIONS TO SCHOOLS/COLLEGES General donations to educational establishments which qualify as a charitable organisation under the relevant law may be made with charitable funds provided all tuition charges have been paid.</p> 

    <p>7.	<span class="fw-bold"> SERVICES TEVINI </span> provide you with the following services (the "Services"):</p>

    <p>8.	 •<span class="fw-bold"> TEVINI </span>, if instructed and where possible, claim Gift Aid on your donations and shall add such sums to your Notional Account; • TEVINI will liaise with potential recipients of grants and will carry out appropriate due diligence; • TEVINI will provide the recipient charity your full name including title, voucher/transfer number, date of transfer, your TEVINI account number and any comments that you make for the recipient charity. If you do not wish for TEVINI to provide such information to the recipient charity you must notify TEVINI via email; • TEVINI may from time to time receive a message from a recipient charity directed for your attention. In such circumstances we will  בס"ד forward on such communication. If you do not wish to receive such communications, please notify TEVINI via email; • TEVINI will keep records and accounts regarding your Notional Account for a minimum of 7 years. TEVINI will exercise reasonable skill and care in the provision of the Services. You will ensure that TEVINI is able to communicate with you to the extent necessary in order for TEVINI to provide the Services. You will provide any information required or requested by TEVINI in connection with the operation of the Notional Account or any matter relating to your dealings with TEVINI as soon as practicable and always within one week of such a request. You will inform TEVINI promptly, of any change in your contact details or, where a Gift Aid declaration has been made, circumstances which may affect the ability to claim Gift Aid on your donations. </p>

<p>9.	<span class="fw-bold">OVERDRAWN ACCOUNTS </span> are responsible for ensuring that the balance of your Notional Account exceeds the amounts which you request to be paid to charities from time to time whether by the issue by you of a voucher to a charity or otherwise. To the extent that your Notional Account does not hold sufficient funds to satisfy a request for a payment to be made to a charity, such payment may not be made. TEVINI will not be responsible for notifying you of the balance of your Notional Account and owes no duty of care to either you or any other party in this regard. In the event that a request is made by you for a payment to be made to a charity for an amount which exceeds the balance of your Notional Account, in its absolute discretion, TEVINI may choose to make the donation on your behalf and full payment has to be made within 30 days, or advise such charity that there is no funds in your Notional Account or the voucher which you have issued to the charity may be returned. TEVINI reserves the right to levy an additional charge as an admin fee to you in all such cases. In the event that amounts have been requested to be paid to a number of charities, TEVINI has absolute discretion in relation to the priority of payment. 8. GRANT REQUESTS TEVINI will use its best endeavours to make payments requested of it as soon as is practicably possible but shall be under no obligation to do so. Requests made by phone/email should not be regarded as having been made unless you receive formal email acknowledgement of such request from TEVINI. Once you have submitted a grant request to TEVINI, this cannot be amended other than by an email request to TEVINI during office hours. Following consideration of all relevant factors, the decision of TEVINI as to whether to amend the grant request shall be final and binding.</p> 

<p>10.	<span class="fw-bold"> BLANK VOUCHERS</span> Vouchers should be issued by you with the name of the payee being stated. TEVINI reserves the right to refuse to pay any voucher where the payee’s name is omitted, altered or in a different handwriting to the rest of the voucher unless that amendment is signed by you.</p> 

<p>11.<span class="fw-bold">	FORGED / EXPIRED VOUCHERS</span> Checks made on the validity, the date and the signature on a voucher presented for payment are limited. Pre-paid vouchers are processed automatically and are not checked. TEVINI has no liability to you in the event that it honours a voucher which is found to be forged, expired or fraudulent.</p>

<p>12.	<span class="fw-bold"> YOUR IDENTITY / CONFIDENTIALITY TEVINI</span> may at its absolute discretion pursuant to its data protection policy and privacy notice, reveal your name to the beneficiary of the donation. TEVINI may undertake checks on your identity by way of third party providers such as credit reference and fraud prevention agencies to manage your account with us. Where you are a corporate entity, TEVINI will only accept instructions, including grant requests, from an individual appointed by you as a signatory using the authorisation form provided to you by TEVINI. If you wish to change any signatory at any time you must complete a new form and TEVINI will update its records as soon as reasonably practicable. TEVINI will only cease to take instructions from a previously appointed signatory, or accept instructions from a new signatory, once its records have been updated.</p>

 <p>13.	<span class="fw-bold">DEATH</span> paragraph does not apply if you are a corporate entity. In the event of your death, TEVINI may, in its discretion, allow your relatives to make requests regarding the allocation of funds held in your Notional Account following your death.</p>

<p>14.	 <span class="fw-bold">COMPLIANCE </span> may be asked to confirm in writing that they receive no benefit from a donation which they request be made by TEVINI. Donors may also be asked other compliance questions at the discretion of TEVINI. The recipient charity may also be asked to confirm that no benefit has/will result, as well as questions pertaining to their relationship with you. Details of the charity/project may also be requested to satisfy money laundering and other compliance requirements.</p>

	
<p>16.	<span class="fw-bold">DORMANT ACCOUNTS</span></p>

<p>17.	<span class="fw-bold"> TEVINI </span> not operating a bank and is established for the purposes of making charitable donations. In the event that funds which have been donated by you are not subsequently the subject of a request to be distributed to a charity within 24 months, TEVINI may, in its discretion, use such funds to make allocations to charities of its own choice without further notification to you.</p>

<p>18.	<span class="fw-bold"> DATA PROTECTION</span> In this Clause “Data” means all Personal Data and other data processed by TEVINI as a result of, or in connection with, the provision of the Services. “Data Protection Laws” means the Electronic Communications (EC Directive) Regulations 2003, the General Data Protection Regulations 2017, the Data Protection Act 2017 and any other data protection laws and regulations applicable in the UK and any codes of practice, בס"ד guidelines or recommendations issued by the Information Commissioner or any replacement body. TEVINI will comply with the requirements of the Data Protection Laws in respect of the activities which are the subject of the contract between you and TEVINI and shall not knowingly do anything or permit anything to be done which might lead to a breach of the Data Protection Laws. TEVINI will process Data for the purposes of carrying out the Services. TEVINI shall only process Data in accordance with its Data Protection Policy and Privacy Policy as amended from time to time and shall not process Data for any other purpose. TEVINI shall have in place all appropriate technological and organizational measures against unauthorized or unlawful use of, access to, or theft of Data and against loss or destruction of, or damage to, Data. You confirm that you have the consent from the third parties of whom you provide TEVINI with their Personal Information, for TEVINI to hold this information in accordance with its Privacy Policy. You may request confirmation of the information we hold about you, to which we will respond within 30 days. The information you have provided is subject to the Data Protection Act 2017, the Data Protection Policy and Privacy Policy of TEVINI as updated from time-to-time. Our Data Protection Policy and Privacy Policy will be reviewed on a regular basis and may be updated from time-to-time. We will notify you via email when this happens and provide you with a copy of the most recent and up-to-date Privacy Policy which is available on our website. 16. COMPLIANCE OFFICER TEVINI’s Compliance Officer is authorized to inspect any transaction. He/she may contact a client to confirm details of a payment and/or to request additional information.</p> 

<p>19.	<span class="fw-bold">SCALE OF CHARGES TEVINI M</span> a standard fee of 5% of all payments made into your Notional Account, and may be reduced for larger donations. By making a payment to TEVINI, you irrevocably authorize TEVINI to levy such a fee. TEVINI reserve the right to periodically review the fee and any changes to the fee will be communicated to you in writing. Additional fees may be due in accordance with paragraphs 2 and 8. All fees will reduce the balance of your Notional Account.</p>

<p>20.	 <span class="fw-bold">AMENDMENT OF THESE TERMS TEVINI </span>, at its absolute discretion, vary these Terms and Conditions. Any such variation will be effective 30 days after you have received written notice of it, which may be made via email or by post at the discretion of TEVINI.</p>

<p>21.	<span class="fw-bold"> LIMITATION OF LIABILITY</span> Funds credited to a Notional Account are owned by TEVINI. In the event that such funds are lost, for example, as a result of the insolvency of a bank with which TEVINI has made deposits, you will have no recourse to TEVINI in respect of such loss.</p> 

<p>22.	 <span class="fw-bold">TERMINATION OF ARRANGEMENT</span> You or TEVINI may terminate this contract at any time by giving one month's written notice to the other party. TEVINI may terminate this contract with immediate effect by way of written notice to you if you commit a material breach of these Terms and Conditions; which includes but is not limited to you providing TEVINI with any information, which in the opinion of TEVINI, is misleading or inaccurate. This contract will terminate automatically if the Notional Account does not contain sufficient funds to cover TEVINI’s fees and costs as set out in Clause 17. During the relevant notice period, TEVINI shall allocate the funds in the Notional Account in accordance with paragraph 4 and will have regard to your requests pursuant to paragraph 3. This contract will terminate automatically on your death or, if you are a corporate entity, you take any step or action in connection with: entering administration, provisional liquidation or any composition or arrangement with your creditors (other than in relation to a solvent restructuring of which you have made us aware); being wound up (whether voluntarily or by order of the court, unless for the purpose of a solvent restructuring of which you have made us aware); having a receiver appointed to any of your assets; or ceasing to carry on business. In any of these cases TEVINI will allocate any remaining funds in your Notional Account in accordance with paragraph 4 and, if relevant, 12 of these Terms and Conditions. The termination of this contract shall not affect any rights or obligations: (a) accrued before the date of termination; or (b) expressed or intended to continue in force after and despite termination.</p>

<p>23.<span class="fw-bold">	ENTIRE AGREEMENT</span> These Terms and Conditions read in conjunction with our Privacy Policy as updated from time to time. These documents are available on request by email and form the entire agreement between the parties and replace all previous agreements and understandings between them, relating to its subject matter.</p>

<p>24.	 Last update: Feb ‘22</p>

</div>
@endsection


